
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.69.0
  FORC_VERSION: 0.40.1
  
jobs:
  test-redstone-fuel-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: Swatinem/rust-cache@v2
      - name: Install Forc
        run: cargo install forc --version ${{ env.FORC_VERSION }}
      - name: Test RedStone Fuel SDK
        run: forc test
